services:
  valkey:
    image: "valkey/valkey:7.2.5-alpine"
    ports:
      - "6379:6379"

  postgres:
    image: "postgres:16.3-alpine3.19"
    environment:
      POSTGRES_USER: "medication"
      POSTGRES_PASSWORD: "medication"
      POSTGRES_DB: "medication_db"
    ports:
      - "5432:5432"
